Repository distkv-project/distkv, pull requests merged in 2019-12, with the labels that each got.

#291 Introduce drpc to replace brpc
  .travis.yml
  client/src/main/java/com/distkv/dst/client/DefaultDstClient.java
  client/src/main/java/com/distkv/dst/client/DstListProxy.java
  client/src/main/java/com/distkv/dst/client/DstSetProxy.java
  client/src/main/java/com/distkv/dst/client/DstStringProxy.java
  common/src/main/java/com/distkv/dst/common/utils/Utils.java
  rpc/pom.xml
  rpc/src/main/java/com/distkv/dst/rpc/service/DstDictService.java
  rpc/src/main/java/com/distkv/dst/rpc/service/DstListService.java
  rpc/src/main/java/com/distkv/dst/rpc/service/DstSetService.java
  rpc/src/main/java/com/distkv/dst/rpc/service/DstSortedListService.java
  rpc/src/main/java/com/distkv/dst/rpc/service/DstStringService.java
  scripts/install_dependencies.sh
  server/src/main/java/com/distkv/dst/server/service/DstListServiceImpl.java
  server/src/main/java/com/distkv/dst/server/service/DstRpcServer.java
  server/src/main/java/com/distkv/dst/server/service/DstSetServiceImpl.java
  server/src/main/java/com/distkv/dst/server/service/DstStringServiceImpl.java
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/server/service/DictRpcTest.java
  test/src/test/java/com/distkv/dst/test/server/service/ListRpcTest.java
  test/src/test/java/com/distkv/dst/test/server/service/SetRpcTest.java
  test/src/test/java/com/distkv/dst/test/server/service/StringRpcTest.java
  test/src/test/java/com/distkv/dst/test/supplier/ListRpcTestUtil.java
  test/src/test/java/com/distkv/dst/test/supplier/ProxyOnClient.java
  test/src/test/java/com/distkv/dst/test/supplier/TestUtil.java
Labels: feature request

#296 Fix command line tool
  client/pom.xml
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandLineToolStarter.java
  scripts/run_dst_cli.sh
Labels: bug

#301 Fix install_dependencies.sh
  scripts/install_dependencies.sh
Labels: bug

#290 Introduce Dmeta Module to Dst
  .gitignore
  dmeta/pom.xml
  dmeta/src/main/java/com/distkv/dmeta/client/DmetaClient.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/CounterClient.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/CounterServer.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/CounterStateMachine.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/IncrementAndAddClosure.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/rpc/GetValueRequest.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/rpc/GetValueRequestProcessor.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/rpc/IncrementAndGetRequest.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/rpc/IncrementAndGetRequestProcessor.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/rpc/ValueResponse.java
  dmeta/src/main/java/com/distkv/dmeta/example/counter/snapshot/CounterSnapshotFile.java
  dmeta/src/main/java/com/distkv/dmeta/server/DmetaServer.java
  dmeta/src/main/java/com/distkv/dmeta/server/DmetaStoreClosure.java
  dmeta/src/main/java/com/distkv/dmeta/server/bean/GetValueRequest.java
  dmeta/src/main/java/com/distkv/dmeta/server/bean/GetValueResponse.java
  dmeta/src/main/java/com/distkv/dmeta/server/bean/PutKVRequest.java
  dmeta/src/main/java/com/distkv/dmeta/server/bean/PutKVResponse.java
  dmeta/src/main/java/com/distkv/dmeta/server/bean/PutKVType.java
  dmeta/src/main/java/com/distkv/dmeta/server/processor/GetValueRequestProcessor.java
  dmeta/src/main/java/com/distkv/dmeta/server/processor/PutKVRequestProcessor.java
  dmeta/src/main/java/com/distkv/dmeta/server/snapshot/DmetaSnapshotFile.java
  dmeta/src/main/java/com/distkv/dmeta/server/statemachine/DataSpace.java
  dmeta/src/main/java/com/distkv/dmeta/server/statemachine/DmetaStateMachine.java
  dmeta/src/main/java/com/distkv/dmeta/server/statemachine/NameSpace.java
  dmeta/src/main/java/com/distkv/dmeta/server/statemachine/SpaceInterface.java
  dmeta/src/main/java/com/distkv/dmeta/server/statemachine/SpaceType.java
  pom.xml
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/dmeta/client/TestServer.java
  test/src/test/java/com/distkv/dst/test/dmeta/store/TestStore.java
  test/src/test/java/com/distkv/dst/test/supplier/DmetaTestUtil.java
Labels: dmeta

#311 Support NodeId, PartitionId and ShardId
  common/src/main/java/com/distkv/dst/common/id/NodeId.java
  common/src/main/java/com/distkv/dst/common/id/PartitionId.java
  common/src/main/java/com/distkv/dst/common/id/ShardId.java
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/common/id/IdTest.java
Labels: feature request

#315 Fix operation command about listDelete and listMDelete
  parser/src/main/java/com/distkv/dst/parser/DstNewSQL.g4
  parser/src/main/java/com/distkv/dst/parser/DstNewSqlListener.java
  test/src/test/java/com/distkv/dst/test/parser/ParseListCommandTest.java
Labels: enhancement

#314 Support string handler on new `Dst Executor` with worker pool
  common/src/main/java/com/distkv/dst/common/NodeInfo.java
  common/src/main/java/com/distkv/dst/common/RequestTypeEnum.java
  parser/src/main/java/com/distkv/dst/parser/DstNewSqlListener.java
  parser/src/main/java/com/distkv/dst/parser/po/DstParsedResult.java
  server/src/main/java/com/distkv/dst/server/runtime/DstRuntime.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/InternalRequest.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/NodeInstance.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/WorkerPool.java
  server/src/main/java/com/distkv/dst/server/service/DstServer.java
  server/src/main/java/com/distkv/dst/server/service/DstStringServiceImpl.java
  test/src/test/java/com/distkv/dst/test/parser/ParseDictCommandTest.java
  test/src/test/java/com/distkv/dst/test/parser/ParseListCommandTest.java
  test/src/test/java/com/distkv/dst/test/parser/ParseStringCommandTest.java
  test/src/test/java/com/distkv/dst/test/supplier/BaseTestSupplier.java
Labels: distributed, feature request

#317 Separate GetAll、GetOne、GetRange operation in parser
  parser/src/main/java/com/distkv/dst/parser/DstNewSqlListener.java
Labels: parser

#319 Hotfix client disconnect
  client/src/main/java/com/distkv/dst/client/DefaultDstClient.java
Labels: bug

#321 Enable set on new DstExecutor
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/dst/server/service/DstServer.java
  server/src/main/java/com/distkv/dst/server/service/DstSetServiceImpl.java
Labels: distributed

#322 Supported SortedList concept in parser and CLT
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandExecutor.java
  common/src/main/java/com/distkv/dst/common/RequestTypeEnum.java
  parser/src/main/java/com/distkv/dst/parser/DstNewSQL.g4
  parser/src/main/java/com/distkv/dst/parser/DstNewSqlListener.java
  test/src/test/java/com/distkv/dst/test/parser/ParseSortedListCommandTest.java
Labels: new feature

#318 Add Async Client
  client/src/main/java/com/distkv/dst/asyncclient/DefaultAsyncClient.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncClient.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncDictProxy.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncListProxy.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncSetProxy.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncSortedListProxy.java
  client/src/main/java/com/distkv/dst/asyncclient/DstAsyncStringProxy.java
  client/src/main/java/com/distkv/dst/client/CheckStatusUtil.java
  client/src/main/java/com/distkv/dst/client/DstDictProxy.java
  client/src/main/java/com/distkv/dst/client/DstListProxy.java
  client/src/main/java/com/distkv/dst/client/DstSetProxy.java
  client/src/main/java/com/distkv/dst/client/DstSortedListProxy.java
  client/src/main/java/com/distkv/dst/client/DstStringProxy.java
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandExecutor.java
  server/pom.xml
  test/src/test/java/com/distkv/dst/test/client/AsyncDictProxyTest.java
  test/src/test/java/com/distkv/dst/test/client/AsyncListProxyTest.java
  test/src/test/java/com/distkv/dst/test/client/AsyncSetProxyTest.java
  test/src/test/java/com/distkv/dst/test/client/AsyncSortedListTest.java
  test/src/test/java/com/distkv/dst/test/client/AsyncStrProxyTest.java
  test/src/test/java/com/distkv/dst/test/supplier/BaseTestSupplier.java
Labels: new feature

#336 Add install_dependencies.bat
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandExecutor.java
  scripts/install_dependencies_win.bat
Labels: enhancement

#334 Add DstCommandExecutor Handler
  client/src/main/java/com/distkv/dst/client/commandlinetool/CommandExecutorHandler.java
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandExecutor.java
Labels: code clean

#337 Remove unused dependency raft-java
  core/pom.xml
Labels: code clean

#342 Enable dict on new DstExecutor
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/dst/server/service/DstDictServiceImpl.java
  server/src/main/java/com/distkv/dst/server/service/DstServer.java
Labels: distributed

#348 Remove unnecessary log
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
Labels: code clean

#350 Use HashMap instead of ConcurrentHashMap
  core/src/main/java/com/distkv/dst/core/DstConcurrentHashMapImpl.java
  core/src/main/java/com/distkv/dst/core/DstHashMapImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstDictImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstListImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstSetImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstSortedListImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstStringImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstTableImpl.java
  test/src/test/java/com/distkv/dst/test/core/multithread/KVSDictMultiThreadTest.java
  test/src/test/java/com/distkv/dst/test/core/multithread/KVSListMultiThreadTest.java
  test/src/test/java/com/distkv/dst/test/core/multithread/KVSMultiThreadTestBase.java
  test/src/test/java/com/distkv/dst/test/core/multithread/KVSSetMultiThreadTest.java
  test/src/test/java/com/distkv/dst/test/core/multithread/KVSStrMultiThreadTest.java
Labels: distributed

#352 Refactor the Dst Core
  core/src/main/java/com/distkv/dst/core/KVStore.java
  core/src/main/java/com/distkv/dst/core/KVStoreImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstDictImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstDictsImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstListsImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstSetImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstSetsImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstSortedListsImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstStringImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstStringsImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstTablesImpl.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstConcepts.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstDicts.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstLists.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstSets.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstSortedLists.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstStrings.java
  core/src/main/java/com/distkv/dst/core/operatorset/DstTables.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/dst/server/service/DstServer.java
  test/src/test/java/com/distkv/dst/test/core/operator/KVSDictTest.java
  test/src/test/java/com/distkv/dst/test/core/operator/KVSListTest.java
  test/src/test/java/com/distkv/dst/test/core/operator/KVSStrTest.java
Labels: code clean

#365 Fix the bug of out of index of the the shard index
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/WorkerPool.java
Labels: bug

#366 Fix partial capitalization of nouns in README
  README.md
Labels: enhancement

#371 Rename package name to `concepts`
  core/src/main/java/com/distkv/dst/core/KVStore.java
  core/src/main/java/com/distkv/dst/core/KVStoreImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstConcepts.java
  core/src/main/java/com/distkv/dst/core/concepts/DstDicts.java
  core/src/main/java/com/distkv/dst/core/concepts/DstDictsImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstLists.java
  core/src/main/java/com/distkv/dst/core/concepts/DstListsImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSets.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSetsImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSortedLists.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSortedListsImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstStrings.java
  core/src/main/java/com/distkv/dst/core/concepts/DstStringsImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstTables.java
  core/src/main/java/com/distkv/dst/core/concepts/DstTablesImpl.java
  core/src/main/java/com/distkv/dst/core/operatorImpl/DstStringsImpl.java
Labels: code clean

#387 Add configuration files and configuration classes
  scripts/run_dst_server.sh
  server/pom.xml
  server/src/main/java/com/distkv/dst/server/DstServer.java
  server/src/main/java/com/distkv/dst/server/DstServerConfig.java
  server/src/main/java/com/distkv/dst/server/runtime/DstRuntime.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/WorkerPool.java
  server/src/main/java/com/distkv/dst/server/service/DstServer.java
  server/src/main/resources/dst.default.conf
  server/src/main/resources/logback.xml
  test/src/test/java/com/distkv/dst/test/core/operator/KVSSortedListTest.java
  test/src/test/java/com/distkv/dst/test/supplier/TestUtil.java
Labels: enhancement

#394 Bump version to 0.1.2
  client/pom.xml
  common/pom.xml
  core/pom.xml
  dmeta/pom.xml
  fclt/pom.xml
  parser/pom.xml
  pom.xml
  rpc/pom.xml
  scripts/install_dst.sh
  scripts/run_dst_cli.sh
  scripts/run_dst_server.sh
  server/pom.xml
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/supplier/DmetaTestUtil.java
  test/src/test/java/com/distkv/dst/test/supplier/TestUtil.java
Labels: release
