Repository distkv-project/distkv, pull requests merged in 2019-11, with the labels that each got.

#236 Add DstParser module
  .gitignore
  checkstyle-suppressions.xml
  parser/pom.xml
  parser/src/main/java/org/dst/parser/DstNewSQL.g4
  parser/src/main/java/org/dst/parser/DstNewSqlListener.java
  parser/src/main/java/org/dst/parser/DstParser.java
  parser/src/main/java/org/dst/parser/DstSqlErrorListener.java
  parser/src/main/java/org/dst/parser/executor/AbstractExecutor.java
  parser/src/main/java/org/dst/parser/executor/DstSetExecutor.java
  parser/src/main/java/org/dst/parser/po/DstParsedResult.java
  parser/src/main/java/org/dst/parser/util/CodeUtils.java
  parser/src/main/resources/logback.xml
  parser/src/test/java/org/dst/parser/Test.java
  pom.xml
Labels: parser

#240 Move parser test to `test` module
  parser/pom.xml
  parser/src/main/java/org/dst/parser/DstNewSQL.g4
  parser/src/main/java/org/dst/parser/DstSqlErrorListener.java
  parser/src/test/java/org/dst/parser/Test.java
  test/pom.xml
  test/src/test/java/org/dst/test/parser/ParseSetCommandTest.java
Labels: enhancement

#242 Parse `str` and `list` concept
  parser/src/main/java/org/dst/parser/DstNewSQL.g4
  parser/src/main/java/org/dst/parser/DstNewSqlListener.java
  parser/src/main/java/org/dst/parser/po/RequestTypeEnum.java
  test/src/test/java/org/dst/test/parser/ParseListCommandTest.java
  test/src/test/java/org/dst/test/parser/ParseStringCommandTest.java
Labels: parser

#248 Support `DstConcurrentQueue` interface and `DefaultConcurrentQueue`
  common/src/main/java/org/dst/common/queue/DefaultConcurrentQueue.java
  common/src/main/java/org/dst/common/queue/DstConcurrentQueue.java
  test/src/test/java/org/dst/test/common/queue/DefaultConcurrentQueueTest.java
Labels: distributed, feature request

#260 Refactor the semantics of `list.get`
  client/src/main/java/org/dst/client/DstListProxy.java
  common/src/main/java/org/dst/common/exception/DstListIndexOutOfBoundsException.java
  core/src/main/java/org/dst/core/operatorImpl/DstListImpl.java
  core/src/main/java/org/dst/core/operatorset/DstList.java
  parser/src/main/java/org/dst/parser/DstNewSQL.g4
  parser/src/main/java/org/dst/parser/DstNewSqlListener.java
  rpc/src/main/java/org/dst/rpc/protobuf/common_pb.proto
  rpc/src/main/java/org/dst/rpc/protobuf/list_pb.proto
  server/src/main/java/org/dst/server/service/DstListServiceImpl.java
  test/src/test/java/org/dst/test/core/operator/KVSListTest.java
  test/src/test/java/org/dst/test/parser/ParseListCommandTest.java
  test/src/test/java/org/dst/test/server/service/ListRpcTest.java
Labels: enhancement, feature request

#285 Bump version to 0.1.1
  client/pom.xml
  common/pom.xml
  core/pom.xml
  install_dst.sh
  parser/pom.xml
  pom.xml
  rpc/pom.xml
  scripts/run_dst_cli.sh
  scripts/run_dst_server.sh
  server/pom.xml
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/supplier/TestUtil.java
Labels: release
