Repository distkv-project/distkv, pull requests merged in 2019-08, with the labels that each got.

#58 Add list rpc calls
  .gitignore
  server/src/main/java/org/dst/server/service/DstStringService.java
  server/src/main/java/org/dst/server/service/DstStringServiceImpl.java
  server/src/main/proto/dst_server_protocol.proto
  test/src/main/java/test/org/dst/rpc/DstRpcServerTest.java
Labels: feature request

#62 Use foreach
  server/src/main/java/org/dst/server/service/DstStringServiceImpl.java
  test/src/main/java/test/org/dst/rpc/DstRpcServerTest.java
Labels: code clean

#72 Fix mvn skip tests
  .travis.yml
  README.md
Labels: enhancement

#84 Use try-with-resources to manage proxy connection.
  test/src/test/java/test/org/dst/rpc/ListRpcTest.java
  test/src/test/java/test/org/dst/rpc/ProxyOnClient.java
  test/src/test/java/test/org/dst/rpc/SetRpcTest.java
  test/src/test/java/test/org/dst/rpc/StringRpcTest.java
Labels: enhancement

#85 Support Java client SDK
  client/pom.xml
  client/src/main/java/org/dst/client/DefaultDstClient.java
  client/src/main/java/org/dst/client/DstClient.java
  client/src/main/java/org/dst/client/DstStringProxy.java
  common/pom.xml
  common/src/main/java/org/dst/exception/DstException.java
  common/src/main/java/org/dst/exception/KeyNotFoundException.java
  core/pom.xml
  core/src/main/java/org/dst/core/exception/KeyNotFoundException.java
  core/src/main/java/org/dst/core/operatorImpl/DstSetImpl.java
  core/src/main/java/org/dst/core/operatorImpl/DstStringImpl.java
  core/src/main/java/org/dst/core/operatorset/DstSet.java
  core/src/main/java/org/dst/core/operatorset/DstString.java
  server/src/main/java/org/dst/server/service/DstStringServiceImpl.java
  server/src/main/proto/string_pb.proto
  test/pom.xml
  test/src/test/java/test/org/dst/client/StringProxyTest.java
  test/src/test/java/test/org/dst/core/KVStoreTest.java
Labels: new feature

#93 Support dst-list concept
  common/src/main/java/org/dst/utils/Status.java
  core/src/main/java/org/dst/core/operatorImpl/DstListImpl.java
  core/src/main/java/org/dst/core/operatorset/DstList.java
  server/src/main/java/org/dst/server/service/DstListService.java
  server/src/main/java/org/dst/server/service/DstListServiceImpl.java
  server/src/main/proto/list_pb.proto
  test/src/test/java/test/org/dst/core/KVStoreTest.java
  test/src/test/java/test/org/dst/core/operator/KVSListTest.java
Labels: new feature

#89 add the dict proto file and service
  server/src/main/java/org/dst/server/service/DstDictService.java
  server/src/main/java/org/dst/server/service/DstDictServiceImpl.java
  server/src/main/java/org/dst/server/service/DstRpcServer.java
  server/src/main/proto/dict_pb.proto
  test/src/test/java/test/org/dst/rpc/DictRpcTest.java
Labels: new feature

#95 refactor test module
  common/src/main/java/org/dst/exception/KeyNotFoundException.java
  core/src/main/java/org/dst/core/operatorImpl/DstSetImpl.java
  test/src/test/java/test/org/dst/core/KVStoreTest.java
  test/src/test/java/test/org/dst/core/operator/KVSDictTest.java
  test/src/test/java/test/org/dst/core/operator/KVSListTest.java
  test/src/test/java/test/org/dst/core/operator/KVSSetTest.java
  test/src/test/java/test/org/dst/core/operator/KVSStrTest.java
Labels: enhancement

#109 Refine the pb message and method names
  client/src/main/java/org/dst/client/DstStringProxy.java
  server/src/main/java/org/dst/server/service/DstDictService.java
  server/src/main/java/org/dst/server/service/DstDictServiceImpl.java
  server/src/main/java/org/dst/server/service/DstListService.java
  server/src/main/java/org/dst/server/service/DstListServiceImpl.java
  server/src/main/java/org/dst/server/service/DstSetService.java
  server/src/main/java/org/dst/server/service/DstSetServiceImpl.java
  server/src/main/java/org/dst/server/service/DstStringService.java
  server/src/main/java/org/dst/server/service/DstStringServiceImpl.java
  server/src/main/proto/dict_pb.proto
  server/src/main/proto/list_pb.proto
  server/src/main/proto/set_pb.proto
  server/src/main/proto/string_pb.proto
  test/src/test/java/test/org/dst/rpc/DictRpcTest.java
  test/src/test/java/test/org/dst/rpc/ListRpcTest.java
  test/src/test/java/test/org/dst/rpc/SetRpcTest.java
  test/src/test/java/test/org/dst/rpc/StringRpcTest.java
Labels: enhancement

#86 Add other set rpc operations
  core/src/main/java/org/dst/core/operatorImpl/DstSetImpl.java
  core/src/main/java/org/dst/core/operatorset/DstSet.java
  server/src/main/java/org/dst/server/service/DstSetService.java
  server/src/main/java/org/dst/server/service/DstSetServiceImpl.java
  server/src/main/proto/set_pb.proto
  test/src/test/java/test/org/dst/core/KVStoreTest.java
  test/src/test/java/test/org/dst/core/operator/KVSSetTest.java
  test/src/test/java/test/org/dst/rpc/ListRpcTest.java
  test/src/test/java/test/org/dst/rpc/SetRpcTest.java
  test/src/test/java/test/org/dst/rpc/StringRpcTest.java
Labels: new feature

#127 List refactor
  core/src/main/java/org/dst/core/operatorImpl/DstListImpl.java
  server/src/main/java/org/dst/server/service/DstListService.java
  server/src/main/java/org/dst/server/service/DstListServiceImpl.java
  server/src/main/proto/list_pb.proto
  test/src/test/java/test/org/dst/server/service/ListRpcTest.java
  test/src/test/java/test/org/dst/supplier/ListRpcTestUtil.java
Labels: enhancement

#153 Remove git file
  git
Labels: code clean
