Repository distkv-project/distkv, pull requests merged in 2019-09, with the labels that each got.

#144 Stress Test ( DST vs RDS )
  client/src/main/java/org/dst/client/DefaultDstClient.java
  test/pom.xml
  test/src/test/java/test/org/dst/benchmark/DSTBenchmark.java
  test/src/test/java/test/org/dst/benchmark/DstBenchmarkTest.java
  test/src/test/java/test/org/dst/benchmark/RdsBenchmarkTest.java
  test/src/test/java/test/org/dst/benchmark/core/Benchmark.java
  test/src/test/java/test/org/dst/supplier/TestUtil.java
Labels: perf

#145 Implement client tool
  client/src/main/java/org/dst/client/cmd/ClientResult.java
  client/src/main/java/org/dst/client/cmd/DictHandler.java
  client/src/main/java/org/dst/client/cmd/DstCmdStarter.java
  client/src/main/java/org/dst/client/cmd/DstCommandWithType.java
  client/src/main/java/org/dst/client/cmd/DstOperationType.java
  client/src/main/java/org/dst/client/cmd/Handler.java
  client/src/main/java/org/dst/client/cmd/ListHandler.java
  client/src/main/java/org/dst/client/cmd/Parser.java
  client/src/main/java/org/dst/client/cmd/SetHandler.java
  client/src/main/java/org/dst/client/cmd/StringHandler.java
  client/src/main/java/org/dst/client/cmd/TableHandler.java
Labels: feature request

#174 Add build docs
  docs/build.md
  docs/index.md
Labels: docs

#205 Refine code and doc comments.
  .gitignore
  common/src/main/java/org/dst/common/exception/DictKeyNotFoundException.java
  common/src/main/java/org/dst/common/exception/DstException.java
  common/src/main/java/org/dst/common/exception/KeyNotFoundException.java
  common/src/main/java/org/dst/common/exception/NotImplementException.java
  common/src/main/java/org/dst/common/utils/Status.java
  common/src/main/java/org/dst/common/utils/StringUtil.java
  core/src/main/java/org/dst/core/KVStore.java
  core/src/main/java/org/dst/core/operatorset/DstDict.java
  install_dst.sh
  scripts/run_dst_cli.sh
  scripts/run_dst_server.sh
Labels: code clean

#155 Support table concept in core module
  common/src/main/java/org/dst/common/exception/DuplicatedPrimaryKeyException.java
  common/src/main/java/org/dst/common/exception/IncorrectRecordFormatException.java
  common/src/main/java/org/dst/common/exception/IncorrectTableFormatException.java
  common/src/main/java/org/dst/common/exception/TableAlreadyExistsException.java
  common/src/main/java/org/dst/common/exception/TableNotFoundException.java
  core/src/main/java/org/dst/core/operatorImpl/DstTableImpl.java
  core/src/main/java/org/dst/core/operatorset/DstTable.java
  core/src/main/java/org/dst/core/table/DoubleValue.java
  core/src/main/java/org/dst/core/table/Field.java
  core/src/main/java/org/dst/core/table/Index.java
  core/src/main/java/org/dst/core/table/IntValue.java
  core/src/main/java/org/dst/core/table/RawValue.java
  core/src/main/java/org/dst/core/table/Record.java
  core/src/main/java/org/dst/core/table/StrListValue.java
  core/src/main/java/org/dst/core/table/StrValue.java
  core/src/main/java/org/dst/core/table/TableEntry.java
  core/src/main/java/org/dst/core/table/TableSpecification.java
  core/src/main/java/org/dst/core/table/Value.java
  core/src/main/java/org/dst/core/table/ValueType.java
  test/src/test/java/org/dst/test/core/operator/KVSTableTest.java
Labels: table
