Repository distkv-project/distkv, pull requests merged in 2020-02, with the labels that each got.

#485 Remove legacy table concept
  core/src/main/java/com/distkv/core/KVStore.java
  core/src/main/java/com/distkv/core/KVStoreImpl.java
  core/src/main/java/com/distkv/core/concepts/DistKVTables.java
  core/src/main/java/com/distkv/core/concepts/DistKVTablesImpl.java
  core/src/main/java/com/distkv/core/table/DoubleValue.java
  core/src/main/java/com/distkv/core/table/Field.java
  core/src/main/java/com/distkv/core/table/Index.java
  core/src/main/java/com/distkv/core/table/IntValue.java
  core/src/main/java/com/distkv/core/table/RawValue.java
  core/src/main/java/com/distkv/core/table/Record.java
  core/src/main/java/com/distkv/core/table/StrListValue.java
  core/src/main/java/com/distkv/core/table/StrValue.java
  core/src/main/java/com/distkv/core/table/TableEntry.java
  core/src/main/java/com/distkv/core/table/TableSpecification.java
  core/src/main/java/com/distkv/core/table/Value.java
  core/src/main/java/com/distkv/core/table/ValueType.java
  core/src/test/java/com/distkv/core/operator/KVSTableTest.java
Labels: code clean

#493 Refine codebase
  scripts/install_dependencies.sh
  scripts/install_dependencies_win.bat
  server/src/main/java/com/distkv/server/storeserver/StoreServer.java
Labels: code clean

#504 Support namespace filter for client to allow key conflicts
  client/src/main/java/com/distkv/asyncclient/DefaultAsyncClient.java
  client/src/main/java/com/distkv/asyncclient/DistkvAbstractAsyncProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncClient.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncDictProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncListProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncSetProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncSortedListProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncStringProxy.java
  client/src/main/java/com/distkv/namespace/NamespaceInterceptor.java
  test/src/test/java/com/distkv/client/NamespaceTest.java
Labels: new feature

#508 Add namespace command executor
  client/src/main/java/com/distkv/client/DefaultDistkvClient.java
  client/src/main/java/com/distkv/client/DistkvClient.java
  client/src/main/java/com/distkv/client/commandlinetool/CommandExecutorHandler.java
  client/src/main/java/com/distkv/client/commandlinetool/DistkvCommandExecutor.java
  parser/src/main/java/com/distkv/parser/DistkvNewSQL.g4
  parser/src/main/java/com/distkv/parser/DistkvNewSqlListener.java
  rpc/src/main/java/com/distkv/rpc/protobuf/distkv_pb.proto
  test/src/test/java/com/distkv/client/commandlinetool/DistkvCommandExecutorHandlerTest.java
Labels: new feature

#507 The POC of non heap hash map for store.
  common/src/main/java/com/distkv/common/utils/ByteUtil.java
  core/src/main/java/com/distkv/core/block/Block.java
  core/src/main/java/com/distkv/core/block/BlockPool.java
  core/src/main/java/com/distkv/core/map/ByteSegment.java
  core/src/main/java/com/distkv/core/map/DistkvNonHeapHashMapImpl.java
  core/src/main/java/com/distkv/core/map/DistkvOffHeapMapMeta.java
  core/src/main/java/com/distkv/core/map/DoubleSegment.java
  core/src/main/java/com/distkv/core/map/FixedValueSegment.java
  core/src/main/java/com/distkv/core/map/FloatSegment.java
  core/src/main/java/com/distkv/core/map/FnvHash.java
  core/src/main/java/com/distkv/core/map/HashFunction.java
  core/src/main/java/com/distkv/core/map/IntSegment.java
  core/src/main/java/com/distkv/core/map/LongSegment.java
  core/src/main/java/com/distkv/core/map/NonFixedSegment.java
  core/src/main/java/com/distkv/core/map/ShortSegment.java
  core/src/main/java/com/distkv/core/map/ValueSegment.java
  test/src/test/java/com/distkv/core/block/BlockPoolTest.java
  test/src/test/java/com/distkv/core/block/BlockTest.java
  test/src/test/java/com/distkv/core/map/DistkvNonHeapHashMapImplTest.java
  test/src/test/java/com/distkv/core/map/FixedSegmentTest.java
  test/src/test/java/com/distkv/core/map/NonFixedSegmentTest.java
Labels: enhancement

#521 Add deactive namespace method
  client/src/main/java/com/distkv/asyncclient/DefaultAsyncClient.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncClient.java
  client/src/main/java/com/distkv/client/DefaultDistkvClient.java
  client/src/main/java/com/distkv/client/DistkvClient.java
  client/src/main/java/com/distkv/client/commandlinetool/CommandExecutorHandler.java
  client/src/main/java/com/distkv/client/commandlinetool/DistkvCommandExecutor.java
  client/src/main/java/com/distkv/namespace/NamespaceInterceptor.java
  parser/src/main/java/com/distkv/parser/DistkvNewSQL.g4
  parser/src/main/java/com/distkv/parser/DistkvNewSqlListener.java
  rpc/src/main/java/com/distkv/rpc/protobuf/distkv_pb.proto
  test/src/test/java/com/distkv/client/NamespaceTest.java
  test/src/test/java/com/distkv/client/commandlinetool/DistkvCommandExecutorHandlerTest.java
Labels: new feature

#520 [Pine] Support `PineTopper` as a component of distkv ecosystem.
  common/src/main/java/com/distkv/common/id/PineHandleId.java
  common/src/main/java/com/distkv/common/id/ShardId.java
  common/src/test/java/com/distkv/common/id/IdTest.java
  pine/pom.xml
  pine/src/main/java/com/distkv/pine/api/Pine.java
  pine/src/main/java/com/distkv/pine/components/AbstractPineHandle.java
  pine/src/main/java/com/distkv/pine/components/PineTopper.java
  pine/src/main/java/com/distkv/pine/components/PineTopperImpl.java
  pine/src/main/java/com/distkv/pine/components/topper/PineTopper.java
  pine/src/main/java/com/distkv/pine/components/topper/PineTopperImpl.java
  pine/src/main/java/com/distkv/pine/components/topper/TopperMember.java
  pine/src/main/java/com/distkv/pine/runtime/PineRuntime.java
  test/pom.xml
  test/src/test/java/com/distkv/pine/TopperTest.java
  test/src/test/java/com/distkv/supplier/BaseTestSupplier.java
Labels: new feature

#549 Write docs for Distkv
  docs/build.md
  docs/client_tool.md
  docs/command_guide.md
  docs/contributors.md
  docs/details/ErrorCode.md
  docs/install.md
  docs/release_notes.md
  docs/usage.md
  mkdocs.yml
Labels: docs

#569 Add Pine introduction to docs
  docs/index.md
  docs/install.md
  docs/pine.md
Labels: docs
