Repository distkv-project/distkv, pull requests merged in 2020-01, with the labels that each got.

#399 Integrate JMH as a benchmark framework
  test/pom.xml
  test/src/test/java/com/distkv/dst/test/benchmark/SimpleBenchmark.java
  test/src/test/java/com/distkv/dst/test/jmhbenchmark/DstListBenchmark.java
  test/src/test/java/com/distkv/dst/test/jmhbenchmark/DstStrBenchmark.java
  test/src/test/java/com/distkv/dst/test/jmhbenchmark/JmhRunner.java
  test/src/test/java/com/distkv/dst/test/jmhbenchmark/RedisStrBenchmark.java
Labels: perf

#378 Implement DstSortedListLinkedImpl for sorted list
  client/src/main/java/com/distkv/dst/client/CheckStatusUtil.java
  client/src/main/java/com/distkv/dst/client/DstSortedListProxy.java
  client/src/main/java/com/distkv/dst/client/commandlinetool/DstCommandLineToolStarter.java
  common/src/main/java/com/distkv/dst/common/entity/sortedList/SortedListEntity.java
  common/src/main/java/com/distkv/dst/common/exception/DictKeyNotFoundException.java
  common/src/main/java/com/distkv/dst/common/exception/DstException.java
  common/src/main/java/com/distkv/dst/common/exception/DstKeyDuplicatedException.java
  common/src/main/java/com/distkv/dst/common/exception/DstListIndexOutOfBoundsException.java
  common/src/main/java/com/distkv/dst/common/exception/ErrorCodeEnum.java
  common/src/main/java/com/distkv/dst/common/exception/KeyNotFoundException.java
  common/src/main/java/com/distkv/dst/common/exception/SortedListIncrScoreOutOfRangeException.java
  common/src/main/java/com/distkv/dst/common/exception/SortedListMemberNotFoundException.java
  common/src/main/java/com/distkv/dst/common/exception/SortedListMembersDuplicatedException.java
  common/src/main/java/com/distkv/dst/common/exception/SortedListTopNumIsNonNegativeException.java
  core/src/main/java/com/distkv/dst/core/KVStore.java
  core/src/main/java/com/distkv/dst/core/KVStoreImpl.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSortedLists.java
  core/src/main/java/com/distkv/dst/core/concepts/DstSortedListsImpl.java
  core/src/main/java/com/distkv/dst/core/struct/slist/SortedList.java
  core/src/main/java/com/distkv/dst/core/struct/slist/SortedListLinkedImpl.java
  server/src/main/java/com/distkv/dst/server/runtime/workerpool/Worker.java
  test/src/test/java/com/distkv/dst/test/benchmark/core/concepts/DstSortedListsImplSimpleBenchmark.java
  test/src/test/java/com/distkv/dst/test/client/AsyncDictProxyTest.java
  test/src/test/java/com/distkv/dst/test/client/AsyncSortedListTest.java
  test/src/test/java/com/distkv/dst/test/common/entity/sortedList/SortedListEntityTest.java
  test/src/test/java/com/distkv/dst/test/core/operator/KVSSortedListTest.java
  test/src/test/java/com/distkv/dst/test/core/struct/slist/SortedListLinkedImplTest.java
  test/src/test/java/com/distkv/dst/test/server/service/SortedListRpcTest.java
Labels: enhancement, new feature, perf

#411 Add dst docker
  deploy/docker/Dockerfile
  deploy/docker/README.md
  deploy/docker/docker-compose.yaml
  deploy/docker/dst_start.sh
Labels: enhancement

#423 Enable codecov
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  README.md
  common/src/test/java/com/distkv/dst/common/id/IdTest.java
  common/src/test/java/com/distkv/dst/common/utils/StringUtilTest.java
  mvnw
  mvnw.cmd
  pom.xml
  test/pom.xml
Labels: enhancement

#441 Remove useless code
  common/src/main/java/com/distkv/common/queue/DefaultConcurrentQueue.java
  common/src/main/java/com/distkv/common/queue/DstConcurrentQueue.java
  common/src/test/java/com/distkv/common/queue/DefaultConcurrentQueueTest.java
Labels: code clean

#460 Enable io thread only
  server/src/main/java/com/distkv/server/DstServer.java
Labels: perf

#467 Refine the relationship between worker, worker pool and store runtime
  server/src/main/java/com/distkv/server/base/DistKVBaseService.java
  server/src/main/java/com/distkv/server/runtime/DistKVRuntime.java
  server/src/main/java/com/distkv/server/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/server/runtime/workerpool/WorkerPool.java
Labels: code clean

#468 Fix typo
  server/src/main/java/com/distkv/server/runtime/DistKVRuntime.java
  server/src/main/java/com/distkv/server/runtime/slave/SlaveClient.java
  server/src/main/java/com/distkv/server/runtime/workerpool/Worker.java
  test/src/test/java/com/distkv/client/masterslavesync/TestMasterSyncToSlaves.java
  test/src/test/java/com/distkv/supplier/MasterSlaveSyncTestUtil.java
Labels: code clean

#469 Add the package storeserver
  deploy/python/distkv_server.py
  server/pom.xml
  server/src/main/java/com/distkv/server/runtime/workerpool/NodeInstance.java
  server/src/main/java/com/distkv/server/storeserver/DistKVServerConfig.java
  server/src/main/java/com/distkv/server/storeserver/DstServer.java
  server/src/main/java/com/distkv/server/storeserver/runtime/DistKVRuntime.java
  server/src/main/java/com/distkv/server/storeserver/runtime/slave/SlaveClient.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/InternalRequest.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/NodeInstance.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/WorkerPool.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVDictServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVListServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVSetServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVSortedListServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVStringServiceImpl.java
  test/src/test/java/com/distkv/supplier/MasterSlaveSyncTestUtil.java
  test/src/test/java/com/distkv/supplier/TestUtil.java
Labels: code clean

#471 Rename `Runtime` to `StoreRuntime`
  server/src/main/java/com/distkv/server/storeserver/StoreServer.java
  server/src/main/java/com/distkv/server/storeserver/runtime/StoreRuntime.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/WorkerPool.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVDictServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVListServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVSetServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVSortedListServiceImpl.java
  server/src/main/java/com/distkv/server/storeserver/services/DistKVStringServiceImpl.java
Labels: code clean
