Repository distkv-project/distkv, pull requests merged in 2020-03, with the labels that each got.

#584 Fix Str can't put a int value in command line.
  parser/src/main/java/com/distkv/parser/DistkvNewSQL.g4
Labels: bug

#586 Supports key expired for all data structures
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncClient.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncDictProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncIntProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncListProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncSetProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncSortedListProxy.java
  client/src/main/java/com/distkv/asyncclient/DistkvAsyncStringProxy.java
  client/src/main/java/com/distkv/client/DistkvDictProxy.java
  client/src/main/java/com/distkv/client/DistkvIntProxy.java
  client/src/main/java/com/distkv/client/DistkvListProxy.java
  client/src/main/java/com/distkv/client/DistkvSetProxy.java
  client/src/main/java/com/distkv/client/DistkvSortedListProxy.java
  client/src/main/java/com/distkv/client/DistkvStringProxy.java
  client/src/main/java/com/distkv/client/commandlinetool/CommandExecutorHandler.java
  client/src/main/java/com/distkv/client/commandlinetool/DistkvCommandExecutor.java
  parser/src/main/java/com/distkv/parser/DistkvNewSQL.g4
  parser/src/main/java/com/distkv/parser/DistkvNewSqlListener.java
  rpc/src/main/proto/distkv_pb.proto
  rpc/src/main/proto/expire_pb.proto
  server/src/main/java/com/distkv/server/storeserver/runtime/StoreRuntime.java
  server/src/main/java/com/distkv/server/storeserver/runtime/expire/ExpirationClient.java
  server/src/main/java/com/distkv/server/storeserver/runtime/expire/ExpirationManager.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/Worker.java
  test/src/test/java/com/distkv/client/DictProxyTest.java
  test/src/test/java/com/distkv/client/IntProxyTest.java
  test/src/test/java/com/distkv/client/ListProxyTest.java
  test/src/test/java/com/distkv/client/SetProxyTest.java
  test/src/test/java/com/distkv/client/SortedListProxyTest.java
  test/src/test/java/com/distkv/client/StringProxyTest.java
  test/src/test/java/com/distkv/client/commandlinetool/DistkvCommandExecutorHandlerTest.java
Labels: enhancement

#608 [StorageEngine] Put all data into one map
  core/src/main/java/com/distkv/core/KVStoreImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvConcepts.java
  core/src/main/java/com/distkv/core/concepts/DistkvDictsImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvIntsImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvListsImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvSetsImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvSortedListsImpl.java
  core/src/main/java/com/distkv/core/concepts/DistkvStringsImpl.java
  rpc/src/main/proto/common_pb.proto
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/Worker.java
  test/src/test/java/com/distkv/client/NamespaceTest.java
  test/src/test/java/com/distkv/client/StringProxyTest.java
  test/src/test/java/com/distkv/client/masterslavesync/TestMasterSyncToSlaves.java
  test/src/test/java/com/distkv/supplier/BaseTestSupplier.java
Labels: enhancement

#626 Introduce Jline for distkv command line
  client/pom.xml
  client/src/main/java/com/distkv/client/commandlinetool/DistkvCommandLineToolStarter.java
Labels: enhancement

#648 Code Clean
  client/src/main/java/com/distkv/client/commandlinetool/DistkvCommandLineToolStarter.java
Labels: code clean

#637 Support MetaServer to manage StoreServer
  common/src/main/java/com/distkv/common/NodeInfo.java
  common/src/main/java/com/distkv/common/id/GroupId.java
  common/src/main/java/com/distkv/common/id/NodeId.java
  common/src/main/java/com/distkv/common/utils/NetUtil.java
  common/src/test/java/com/distkv/common/id/IdTest.java
  server/src/main/java/com/distkv/server/metaserver/client/DmetaClient.java
  server/src/main/java/com/distkv/server/metaserver/server/DmetaServer.java
  server/src/main/java/com/distkv/server/metaserver/server/DmetaStoreClosure.java
  server/src/main/java/com/distkv/server/metaserver/server/bean/GetRequest.java
  server/src/main/java/com/distkv/server/metaserver/server/bean/GetResponse.java
  server/src/main/java/com/distkv/server/metaserver/server/bean/HeartbeatRequest.java
  server/src/main/java/com/distkv/server/metaserver/server/bean/HeartbeatResponse.java
  server/src/main/java/com/distkv/server/metaserver/server/bean/PutRequest.java
  server/src/main/java/com/distkv/server/metaserver/server/processor/GetValueRequestProcessor.java
  server/src/main/java/com/distkv/server/metaserver/server/processor/HeartbeatRequestProcessor.java
  server/src/main/java/com/distkv/server/metaserver/server/statemachine/MetaStateMachine.java
  server/src/main/java/com/distkv/server/storeserver/RunningMode.java
  server/src/main/java/com/distkv/server/storeserver/StoreConfig.java
  server/src/main/java/com/distkv/server/storeserver/runtime/StoreRuntime.java
  server/src/main/java/com/distkv/server/storeserver/runtime/heartbeat/HeartbeatManager.java
  server/src/main/java/com/distkv/server/storeserver/runtime/workerpool/Worker.java
  server/src/main/java/com/distkv/server/view/DistkvAbstractView.java
  server/src/main/java/com/distkv/server/view/DistkvGlobalView.java
  server/src/main/java/com/distkv/server/view/NodeTable.java
  server/src/main/java/com/distkv/server/view/ShardTable.java
  server/src/main/resources/store.default.conf
  server/src/test/java/com/distkv/server/storeserver/TestConf.java
  test/conf/master_store.conf
  test/conf/slave_store_1.conf
  test/conf/slave_store_2.conf
  test/conf/test.store.conf
  test/src/test/java/com/distkv/client/masterslavesync/TestMasterSyncToSlaves.java
  test/src/test/java/com/distkv/metaserver/client/TestServer.java
  test/src/test/java/com/distkv/supplier/DmetaTestUtil.java
  test/src/test/java/com/distkv/supplier/MasterSlaveSyncTestUtil.java
Labels: distributed
